### ISSUE TITLE
MPU exception during startup with RPi Pico

### ISSUE THREAD

**Issue by xdthegreat** [micropython-IMU/micropython-mpu9x50#24]
Hardware: Raspberry Pi Pico, MPU-6050

Error message:
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "imu.py", line 105, in __init__
  File "imu.py", line 159, in chip_id
MPUException: I2C failure when communicating with IMU

Suspected bug is in _read() class function. Why try cell is not used in chip_id, following error message is recorded:
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "imu.py", line 105, in __init__
  File "imu.py", line 157, in chip_id
  File "imu.py", line 117, in _read
OSError: [Errno 5] EIO

Not sure if issue is with hardware or code

**Comment by xdthegreat** [comment]
Rebooting the whole thing somehow fixed the system. I apologize for not trying the nuclear option.
